# debug 开关
DEBUG = false

# 代理端口
PORT = 8443

# secret (32 个十六进制字符)
SECRET = 00000000000000000000000000000000

# 模式开关
MODES_CLASSIC = false
MODES_SECURE = true
MODES_TLS = false

# TLS 模式的域，不良客户端在此被代理
# TLS_DOMAIN = itunes.apple.com

# 用于广告的标签，可从 @MTProxybot 获取
# AD_TAG = 
